08: 08.o student.o directory.o lecture.o
	gcc -o 08 08.o student.o directory.o lecture.o
08.o: 08.c student.h lecture.h
	gcc -c 08.c
student.o: student.c
	gcc -c student.c
directory.o: directory.c
	gcc -c directory.c
lecture.o: lecture.c
	gcc -c lecture.c
